### ISSUE TITLE
Display extended information about file access

### ISSUE THREAD

**Issue by alefragnani** [alefragnani/vscode-read-only-indicator#1]
Displaying _RO_\* and **RW** is good, but maybe we could have a bit more. Why not display the full file access mask (numeric and/or characters)?

It should be visible in the **tooltip**

**Comment by tandacedric** [comment]
How to toogle **Read-only** mode in **vscode**?

**Comment by alefragnani** [comment]
Hi @tandacedric ,

It's not possible yet. This https://github.com/alefragnani/vscode-read-only-indicator/issues was created to track it, but it is still openned. 

The main concern is about the complexity of Linux/Mac file access attributes (`chmod`) since Windows has a much simple structure (`attrib`). I didn't decide a _better of both worlds_ to handle it without compromising the Linux/Mac peculiarities.

**Comment by alefragnani** [comment]
I don't have a Mac/Linux to test the whole File Access attribute, so I'm closing it. If someone asks for this in the future, I will ask for PRs.
