### ISSUE TITLE
Support MacOS and Linux

### ISSUE THREAD

**Issue by alefragnani** [alefragnani/vscode-read-only-indicator#12]
MacOS and Linux have different file access concepts (from Windows). To simplify the implementaiton, it would use _user level_ file access.

**Comment by TomChapple** [comment]
I know [there is a fork](https://github.com/dave8927/vscode-read-only-indicator) that implements this extension for Mac. It uses chmod to do it, but the technique is very similar to the current one. I assume the same can be done for Linux.

**Comment by alefragnani** [comment]
Yep, I created this issue because I found that fork, while looking at extension with similar name, to avoid conflict. IMHO, instead of publishing another extension, it should contribute back to mine, but anyway...

In fact, my main problem is to not have access to a MacOS. I had a 2008 MacBook but VS Code is not supported (old OS). Here in Brazil the Apple products are overpriced (double the US base price) and our currency is 1 x 4 USD. Not good 😢

**Comment by alefragnani** [comment]
Closed with PR #13 . 
I will try to release an update later today

**Comment by dave8927** [comment]
> Yep, I created this issue because I found that fork, while looking at extension with similar name, to avoid conflict. IMHO, instead of publishing another extension, it should contribute back to mine, but anyway...

@alefragnani Apologies, I'm not really familiar with how the GitHub system works.  I made the changes for myself really. I wasn’t sure if my modifications were the correct way to implement this feature - though it seemed to work fine for me. Now I've noticed your extension implements this I can remove mine :)

I feel you on the Mac pricing... I have been wanting to upgrade for a while...

**Comment by alefragnani** [comment]
@dave8927 no problem 👍 . 

If you are new to GitHub and how _contribution_ works, I suggest you to take a look at https://help.github.com/en/categories/collaborating-with-issues-and-pull-requests for a better understanding. 

Hope this helps
