### ISSUE TITLE
Feature request: Option/Toggle to make the editor read only when the underlying file is read only.

### ISSUE THREAD

**Issue by henrik-jensen** [alefragnani/vscode-read-only-indicator#20]
There is a long time request for an [Add read-only mode](https://github.com/microsoft/vscode/issues/4873) enhancement request to vscode for a toggle to make the editor (buffer) read only.
I wonder if this extension, as an option, could toggle the [built in readOnly Editor option](https://github.com/microsoft/vscode/blob/2c1c691b06ce90b9517bd3c5e5f518a130c18939/src/vs/editor/common/config/editorOptions.ts#L120), see [[2.]](https://github.com/microsoft/vscode/pull/82748#issuecomment-543730604), when it detects a readonly file?

Some links of possible interest:

1.  A [comment](https://github.com/microsoft/vscode/issues/4873#issuecomment-583775589) by @ctf0 that refers to your extension.
2. A [comment](https://github.com/microsoft/vscode/pull/82748#issuecomment-543730604) by @alexdima on the [rejected read-only mode PR](https://github.com/microsoft/vscode/pull/82748) with a link to the [built in readOnly Editor option](https://github.com/microsoft/vscode/blob/2c1c691b06ce90b9517bd3c5e5f518a130c18939/src/vs/editor/common/config/editorOptions.ts#L120).

**Comment by alefragnani** [comment]
Hi @henrik-jensen ,

Unfortunately not. There is no `readOnly` attribute available, neither a way to _change_ the file access of the editor (buffer) .

I understand that [that issue](https://github.com/microsoft/vscode/issues/4873) is complex, and may have a bunch of scenarios to take care of, but I wonder why _single, read-only files_ aren’t opened as _read-only_ (non editable) yet. BTW, there is an [open issue here](https://github.com/microsoft/vscode/issues/17670). 

Maybe upvoting the last one would make it easier to be released 😃 .

Hope this helps.

PS. Once https://github.com/microsoft/vscode/issues/17670 is release, toggling read-only/writeable would update the editor _automagically_

**Comment by henrik-jensen** [comment]
So the EditorOptions.is [readOnly](https://github.com/microsoft/vscode/blob/e5834d3280fcd04898efeac32b9cf1b893f9b127/src/vs/editor/common/config/editorOptions.ts#L133) property is only available internally and not for extensions? 

Anyway, upvoted [microsoft/vscode#17670](https://github.com/microsoft/vscode/issues/17670)
Maybe there is hope, though that issue is almost as old as [microsoft/vscode#4873](https://github.com/microsoft/vscode/issues/4873).

Thx for the response and link.

**Comment by alefragnani** [comment]
Yes, it is :-(

Let’s see what the VS Code team have planned for the next releases. With so much effort in _Remote Development_ scenarios, maybe we see improvements in FileSystem info, and this `readOnly` attribute may end up with newer APIs.

I have upvoted/subscribed to that issues too..

**Comment by funkiestj** [comment]
As an emacs user, I really love being able to toggle a buffer read only even when the file is writable.  Vim also have the option to open a file as a "read only" buffer (vim -R <file>)

**Comment by alefragnani** [comment]
Hi @funkiestj ,

I'm not an emacs/vim user, but from time to time I also need to _toggle_ read-only state for the buffer, but unfortunately, the VSCode issue https://github.com/microsoft/vscode/issues/4873 is still open, with no ETA.

You may upvote/subscribe on that issue, so you would be notified on updates.

Hope this helps

**Comment by funkiestj** [comment]
> You may upvote/subscribe on that issue, so you would be notified on updates.

upvoted.
