### ISSUE TITLE
[FEATURE] - change all files access

### ISSUE THREAD

**Issue by Byzero512** [alefragnani/vscode-read-only-indicator#32]

**Comment by alefragnani** [comment]
Hi @Byzero512 ,

Could you provide more details about your request?

I mean, would it change just _open_ / _modified_ files? Or do you mean the _file access_ itself (`chmod` attribute)

Thank you

**Comment by Byzero512** [comment]
change modified file's mode to writable automatically.

**Comment by alefragnani** [comment]
I’m not sure about this. I mean, the extension’s initial idea was to be a File Access _indicator_. Yes, today it also has commands to change the file access individually, but making it responsible to _automatically make the file writeable_ could be a little too much.

But, let’s see how other users react. If the issue receives enough attention, it could be added.

Hope this helps.
