### ISSUE TITLE
[FEATURE] Support apply RO mode to folder

### ISSUE THREAD

**Issue by zxbuaa** [alefragnani/vscode-read-only-indicator#36]
Please support folder level mode.

**Comment by alefragnani** [comment]
A new command, available in the `Explorer` panel.

**Comment by k-kuroguro** [comment]
Has anyone already tackled this issue? If not, I'd like do it.

**Comment by alefragnani** [comment]
@k-kuroguro not that I’m aware of. 

Feel free to send a PR 👍
