### ISSUE TITLE
Click on StatusBar to change File Access

### ISSUE THREAD

**Issue by alefragnani** [alefragnani/vscode-read-only-indicator#4]
Allow to change the File Access also clicking in the StatusBar item (today it only works as commands in Command Palette).

Requested in Microsoft/vscode#17621

**Comment by BillDenton** [comment]
Just tested in 0.6.0. Looks good for both making writable and read only.

**Comment by alefragnani** [comment]
Great! Which OS do you use by the way?

**Comment by BillDenton** [comment]
Windows 7 Professional 64bit

**Comment by alefragnani** [comment]
Thanks, I was looking for macOS and Linux experiences, to know if it is also working, since it has a more complex approach for file access.
