### ISSUE TITLE
Change request: Clean up status bar by removing icon and brackets

### ISSUE THREAD

**Issue by BillDenton** [alefragnani/vscode-read-only-indicator#5]
I think it would be cleaner and would occupy less space in the status bar if the icon and brackets ("[" and "]") were removed. The RO and RW have obvious meaning so I don't think the icon is necessary. By doing this it would IMHO remove clutter from the status bar, leaving more space for other items.

**Comment by alefragnani** [comment]
Hi @BillDenton ,

I personally prefer the way it is, but a `config` will not harm 😄

**Comment by BillDenton** [comment]
Thanks. A config would be good.

**Comment by BillDenton** [comment]
Confirmed fixed in 0.5.0
