### ISSUE TITLE
[FEATURE] - Allow configuring read-only paths

### ISSUE THREAD

**Issue by ssbarnea** [alefragnani/vscode-read-only-indicator#52]
As a python engineer I made the mistake of messing python stdlib with some changes or other libraries by not being careful which files I was editing while debugging an app.

It would be great if we could declare some file path as read-only (even if they are not effectively marked as readonly at filesystem level), so we do not end up accidentally messing them.

**Comment by alefragnani** [comment]
Hi @ssbarnea ,

Extensions are not able to define read-only to Editors. In fact, VS Code itself doesn’t have a read-only mode, yet (https://github.com/microsoft/vscode/issues/4873). So, there is no way to accomplish your request.

But, #36 will be available in the next release (thanks to @k-kuroguro ), so you will be able to apply RO to the _filesystem_, right from the Explorer view in VSCode.

Hope this helps
