### ISSUE TITLE
extension not working with virtual workspaces in latest VS Code

### ISSUE THREAD

**Issue by UserXYZ** [alefragnani/vscode-read-only-indicator#74]
Hi there, I just updated my VS Code on Linux, and then installed this extension hoping to emulate the behavior that Notepad++ has for setting some file as read-only while being opened in editor, and keeping that status over restarts.

Unfortunately, even though the extension claims to have support for virtual workspaces, VS Code immediately disables it with error "This extension has been disabled because it does not support virtual workspaces."

Not sure if it's some behind the scenes change in VS Code or the extension is not updated regarding this feature for a while, but it would be super nice if we could get it to run again.

I tried installing few of the other versions, just for the test, but nothing changed, VS Code still disables it right away.

Any suggestions for a workaround or perhaps a way to get some debugging output that might help troubleshoot it?

Thanks
Andrea

**Comment by alefragnani** [comment]
Hi @UserXYZ ,

Wow, I'm sorry but in fact, the extension **does not support** virtual workspaces. It's an error in extension's documentation 😞 .

The extension does support the _proper notification that it supports the API_, so it will display the proper message (support, not support, partially support) in Extensions panel, but the as VS Code does not provide an API to _check if a virtual file is read only or not_, the extension can't properly inform the user about that.

I'll update the README to fix this misinformation. 

Thanks for reporting
