### ISSUE TITLE
[FEATURE] - UI model support only show icon

### ISSUE THREAD

**Issue by tjx666** [alefragnani/vscode-read-only-indicator#76]
```
"fileAccess.uiMode": "iconOnly"
```

Using `pen` icon to represent readable and writeable
Using `pen with cross`  icon represent only readable

**Comment by alefragnani** [comment]
Hi @tjx666 ,

Thanks for your suggestion.

**Comment by alefragnani** [comment]
I wonder if I should replace the 🚫 (`circle-dash`) icon with the new 🔒 (`lock-small`), following the new readonly attribute that VS Code has added a few releases ago.

So, the `fileAccess.uiMode` setting would become:

| uiMode | Readonly | Writeable |
|--|--|--|
| complete | 🔒 [RO] | 🖊️ [RW] |
| simple | [RO] | [RW] |
| iconOnly | 🔒 | 🖊️ |

**Comment by goyalyashpal** [comment]
> 🔒 (`lock-small`), following the new readonly attribute that VS Code has added a few releases ago.


in my humorous opinion, the file modes in `rwx` are more like simple latch, not a key-lock.  but the big corpse keep doing blind-shiny stuff to fool-please their public so, what can we say 😆
