### ISSUE TITLE
[FEATURE] - Read-only via vscode API (alternative mode)

### ISSUE THREAD

**Issue by zardoy** [alefragnani/vscode-read-only-indicator#83]
Hi, I propose to add an alternative mode to extension so it uses vscode API, I believe it would resolve most of issue and make it work on the web:

```ts
// code that implements it
vscode.workspace.onDidChangeTextDocument(({ document, contentChanges }) => {
    const activeEditor = vscode.window.activeTextEditor
    if (activeEditor.document !== document || contentChanges.length === 0) return
    vscode.commands.executeCommand('undo')
    vscode.commands.executeCommand('editor.action.goToLocations', document.uri, new vscode.Position(0, 0), [], '', 'File is read-only')
})

```

![image](https://user-images.githubusercontent.com/46503702/225785541-1497c196-9063-454a-9a83-f2b564a75556.png)

**Comment by alefragnani** [comment]
Hi @zardoy ,

I'm not sure which issues are you referring to but, AFAIK, the `workspace.fs` API still doesn't work for remotes/web, as https://github.com/microsoft/vscode/issues/48659 is still open. BTW, remote support is being tracked in #18.

But, if you have seen any OSS extension dealing with permissions on remotes, you could try applying the same approach here. And if it works, I would be happy with a PR.

Thank you

**Comment by zardoy** [comment]
Hi, @alefragnani

I suggest to introduce a setting, so extension would interrup text changes within editor (as I understand this is the main goal of the extension) instead of touching files in FS, I also wonder how are you going to use `vscode.workspace.fs` API 🤔

**Comment by alefragnani** [comment]
The extension's purpose is not interrupt changes in the editor, but simply display if the current file permission (writable/read only). Ok, it also allows you to change that, but it does on a file system level, not simply the editor.

In fact, read only mode does not exist today in VS Code. Yes, _some_ operations blocks editing, but an effective read only does not exists yet https://github.com/microsoft/vscode/issues/4873.

**Comment by zardoy** [comment]
> In fact, read only mode does not exist today in VS Code. Yes, some operations blocks editing, but an effective read only does not exists yet microsoft/vscode#4873.

This is the exact reason is why I was looking for your extension, anyway thanks for clarifying the fact that this extension is for working with file permissions only.

**Comment by alefragnani** [comment]
No problem 👍
