### ISSUE TITLE
delete merged branches

### ISSUE THREAD

**Issue by goyalyashpal** [alefragnani/vscode-read-only-indicator#86]
https://github.com/alefragnani/vscode-read-only-indicator/branches/all

![image](https://github.com/alefragnani/vscode-read-only-indicator/assets/19423063/4cc13d25-cc56-4da0-82c3-9cb02c076dbb)

**Comment by alefragnani** [comment]
Hi @goyalyashpal ,

I have a kind of attachment to branches and its history, and since GitHub allows free storage, they remains there 😆 

Jokes aside, I never worried about it, since the repo is relative small. 

Hope this helps

**Comment by goyalyashpal** [comment]
thanks for closing as not planned 👍
