### ISSUE TITLE
[Q] Extension front page - how?

### ISSUE THREAD

**Issue by goyalyashpal** [alefragnani/vscode-read-only-indicator#87]
Hey! Thanks a lot for such a nice extension.

I was wondering how did you create this extension showcase page?
I have never seen _anything_ like that before for VS Cod/ium extensions.

It was a welcome change :)

<img src="https://github.com/alefragnani/vscode-read-only-indicator/assets/19423063/15641f68-f4f0-4c8d-b646-4170aef4d8f3" width=800px/>

**Comment by alefragnani** [comment]
Hi @goyalyashpal ,

First of all, thank you for your kind words. I'm glad you like the extension.

About the welcome page, I created it as a Git Submodule [VS Code What's New](https://github.com/alefragnani/vscode-whats-new submodule), so you can import it on your own extension. Simply follow the instructions in its README. You can also look on how it is used here, as a running exemple.

BTW, that submodule was inspired by the GitLens extension

Hope this helps

**Comment by goyalyashpal** [comment]
awesome. thanks a lot for sharing
