### ISSUE TITLE
[FEATURE] Rename "Writeable" to some 2 worded phrase (akin to "Read Only")

### ISSUE THREAD

**Issue by goyalyashpal** [alefragnani/vscode-read-only-indicator#92]
* typing `ro` in command palette shows somewhere: "<tt>File Access: Make ***R***ead ***O***nly</tt>"
* i.e. as it's 2 words: "Read Only", it matches with 2 keys `ro` which is same as what is shown in the status bar icon
* however, the other command is named as: "File Access: Make Writeable" i.e. is one word, so, it doesn't match with `rw` or anything immediately obvious

maybe like "Re Writable" or "Read Writeable" or "RW (writeable)" ...

**Comment by alefragnani** [comment]
Hi @goyalyashpal ,

I think the best option would be to add `[RO]` and `[RW]` as suffix to the commands. 

* `File Access: Make Writeable [RW]`
* `File Access: Make Read Only [RO]`

Hope this helps

**Comment by goyalyashpal** [comment]
> add `[RO]` and `[RW]` as suffix to the commands

yep, that would work 😃

**Comment by goyalyashpal** [comment]
hi. 

is anything done regarding this? :smiley:

**Comment by alefragnani** [comment]
Hi,

No, not at all. Other priorities back then and I totally forgot to return to this (fairly simple) change. 

It should be available in the next release, in a couple of weeks.

Hope this helps
